import { BusinessClient, IndividualClient } from "./types";

export const mockIndividualClients: IndividualClient[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "07700900123",
    addressLine1: "123 High Street",
    city: "London",
    postcode: "SW1A 1AA",
    nationalInsuranceNumber: "QQ123456C",
    hasUtr: true,
    utrNumber: "1234567890",
    employmentStatus: "self_employed",
    clientStatus: "active",
    incomeSources: "Freelance Web Development",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "07700900456",
    addressLine1: "456 Park Avenue",
    city: "Manchester",
    postcode: "M1 1AA",
    nationalInsuranceNumber: "QQ654321A",
    hasUtr: false,
    employmentStatus: "employed",
    clientStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockBusinessClients: BusinessClient[] = [
  {
    id: "1",
    companyName: "Tech Solutions Ltd",
    companyNumber: "12345678",
    utrNumber: "0987654321",
    vatNumber: "123456789",
    responsiblePersonName: "Alice Johnson",
    responsiblePersonEmail: "alice@techsolutions.com",
    responsiblePersonPhone: "02079460123",
    registeredAddressLine1: "Innovation Hub",
    registeredCity: "Cambridge",
    registeredPostcode: "CB1 1AB",
    tradingAddressSame: true,
    clientStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    companyName: "Green Gardens Co",
    companyNumber: "87654321",
    utrNumber: "5678901234",
    responsiblePersonName: "Bob Green",
    responsiblePersonEmail: "bob@greengardens.co.uk",
    responsiblePersonPhone: "01614960123",
    registeredAddressLine1: "The Barn",
    registeredCity: "Leeds",
    registeredPostcode: "LS1 1AB",
    tradingAddressSame: false,
    tradingAddressLine1: "Unit 5, Industrial Estate",
    tradingCity: "Leeds",
    tradingPostcode: "LS2 2CD",
    clientStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
